spring.application.name=LMS_Project

spring.datasource.url= jdbc:postgresql://localhost:5432/lms_db
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.thymeleaf.check-template-location=false
server.port=1515

# JWT Configuration
jwt.secret=secret key should be added
jwt.expiration=time slot